name: tmp4

inputs:
  input_str:
    description: str
    required: false

runs:
  using: 'composite'
  steps:
    - name: echo
      shell: bash
      run: |
        echo "${{ steps.parent.outputs.output }}"
    - name: echo
      shell: bash
      id: child
      run: |
        echo this is an action
        echo "output=hogehoge" | tee -a $GITHUB_OUTPUT
