name: tmp1

inputs:
  input_str:
    description: str
    required: true

runs:
  using: 'composite'
  steps:
    - name: echo
      shell: bash
      env:
        inputs: ${{ toJSON(inputs) }}
      run: |
        echo "${{ inputs.input_str }}"
        echo --------------
        echo "$inputs"
    - name: echo 2
      shell: bash
      env:
        INPUT_STR: ${{ inputs.input_str }}
      run: |
        IFS=$'\n' read -r -d '' -a array <<< "${INPUT_STR}"
        echo --------------
        declare -p array
