name: tmp1

inputs:
  input_str:
    description: str
    required: true

runs:
  using: 'composite'
  steps:
    - name: echo
      shell: bash
      run: |
        echo "${{ inputs.input_str }}"
        echo --------------
        echo "${{ inputs }}"
    - name: echo 2
      shell: bash
      run: |
        IFS=$'\n' read -r -d '' -a array < <(printf '%s\0' "${{ inputs.input_str }}")
        declare -p array
