name: tmp1

inputs:
  input_str:
    description: str
    required: true

runs:
  using: 'composite'
  steps:
    - name: echo
      shell: bash
      env:
        inputs: ${{ toJSON(inputs) }}
      run: |
        echo "${{ inputs.input_str }}"
        echo --------------
        echo "$inputs"
    - name: echo 2
      shell: bash
      run: |
        mapfile -t arr < <(echo "${{ inputs.input_str }}" | sed '/^$/d')
        echo ---------------------
        declare -p arr
