name: tmp1
description: >- 
  asdf
  asdff laksdjf

inputs:
  ref:
    description: 'This is ${ref}'
    required: false
    default: ${{ github.ref }}

runs:
  using: 'composite'
  steps:
    - name: env
      shell: bash
      run: echo "testenv=12345" | tee -a $GITHUB_ENV
