name: tmp1
description: >- 
  asdf
  asdff laksdjf

inputs:
  ref:
    description: "ref"
    required: false
    default: ${{ github.ref }}

runs:
  using: 'composite'
  steps:
    - name: hashFiles
      shell: bash
      working-directory: dir
      run: ls -l && echo ${{ hashFiles('hanako.md') }}
    - name: test
      shell: bash
      run: echo ${{ inputs.ref }}
    - name: continue-on-error
      continue-on-error: true
      shell: bash
      run: exit 1
    - name: after
      shell: bash
      run: echo hello world
