name: array string passing test

on:
  workflow_dispatch:

jobs:
  caller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create array
        id: create_array
        run: |
          set -x
          array=(a b "c d" -e ffff --gh 'i j k')
          printf "%s\n" "${array[@]}"
          echo manu_str1=\"a b \\\"c d\\\" -e ffff --gh \'i j k\'\" | tee $GITHUB_OUTPUT # 'はエスケープ必要 注意
          echo "manu_str2=\"a b \\\"c d\\\" -e ffff --gh 'i j k'\"" | tee $GITHUB_OUTPUT # best
          # 文字列がシングルクオートに囲まれてるときにシングルクオートのエスケープはできない 一度閉じる必要がある

      - name: check opt_str
        run: |
          set -x
          printf "%s\n" ${{steps.create_array.outputs.manu_str1}}
          printf "%s\n" ${{steps.create_array.outputs.manu_str2}}

      - name: call actions
        uses: ./.github/actions/tmp2
        with:
          opt_str: ${{ steps.create_array.outputs.manu_str1 }}

      - name: call actions
        uses: ./.github/actions/tmp2
        with:
          opt_str: ${{ steps.create_array.outputs.manu_str2 }}

      # - name: call actions
      #   uses: ./.github/actions/tmp2
      #   with:
      #     opt_str: ${{ steps.create_array.outputs.opt_str3 }}

      # - name: call actions
      #   uses: ./.github/actions/tmp2
      #   with:
      #     opt_str: ${{ steps.create_array.outputs.opt_str4 }}

      # - name: call actions
      #   uses: ./.github/actions/tmp2
      #   with:
      #     opt_str: ${{ steps.create_array.outputs.opt_str5 }}

      # - name: call actions
      #   uses: ./.github/actions/tmp2
      #   with:
      #     opt_str: ${{ steps.create_array.outputs.opt_str6 }}

      - name: call actions manually (OK)
        uses: ./.github/actions/tmp2
        with:
          opt_str: a b "c d" -e ffff --gh 'i j k'

      # 文字列を''で囲みたいなら({{}}記法のときは必須)、'は''でエスケープする
      - name: call actions manually (OK)
        uses: ./.github/actions/tmp2
        with:
          opt_str: 'a b "c d" -e ffff --gh ''i j k'''