# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      chosen-hello-world:
        required: true
        type: choice
        options:
        - Hello
        - World

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - env:
          ENV_HOGE: hoge
        run: |
          echo echoecho ENV_HOGE=$ENV_HOGE
          printenv | grep ENV_HOGE
      # - run: printenv | grep ENV_HOGE
      - run: ls -R
      - run: mkdir -p path/to/artifact
      - run: echo "hello world" > path/to/artifact/hello.txt
      - run: |
          echo "repo name: ${{github.event.repository.name}}"
          ls -l
          pwd
      - uses: actions/upload-artifact@v4
        with:
          name: hello
          path: path/to/
          if-no-files-found: error
      - run: sleep 10s
      - name: what we want to do
        id: target
        run: sleep 10s

      - run: echo always
        if: ${{ always() }}
      - run: echo failure
        if: ${{ failure() }}
      - run: echo not cancelled
        if: ${{ !cancelled() }}
      - run: echo target state is ${{steps.target.outcome}}
        if: ${{always()}}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo piyo
      - run: echo always job2
        if: ${{ always() }}


  # # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v4

  #     # Runs a single command using the runners shell
  #     - name: Run a one-line script
  #       run: echo Hello, world!

  #     # Runs a set of commands using the runners shell
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
