name: call composite action4

on:
  workflow_dispatch:

jobs:
  call_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: parent
        run: echo "output=parent" | tee -a $GITHUB_OUTPUT
      - run: echo "${{ steps.parent.outputs.output }}"
      - uses: ./.github/actions/tmp4
        #with:
        #  input_str: ""
      - run: |
          echo "${{ steps.child.outputs.output }}"
