name: devcon test

on:
  workflow_dispatch:

jobs:
  devcon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: host info
        run: cat /etc/os-release

      - name: debian devcon
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/debian/devcontainer.json
          runCmd: |
            echo hello from devcontainer
            cat /etc/os-release
            touch testdayo

      - name: debian devcon 2nd
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/debian/devcontainer.json
          runCmd: |
            echo 2nd hello from devcontainer
            ls -la
            pwd

      - name: fedora devcon
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/fedora/devcontainer.json
          runCmd: |
            echo hello from devcontainer
            cat /etc/os-release
            touch fedododo

      - name: fedora 2nd
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/fedora/devcontainer.json
          runCmd: |
            echo 2nd hello from devcontainer
            ls -la
            pwd

  # devcon_manual:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 