name: dispatch_test
env:
  option1: option1 name
on:
  workflow_dispatch:
    inputs:
      mode:
        description: select a mode
        required: true
        type: choice
        options:
          - ${{env.option1}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"

    
