name: dispatch_test
on:
  workflow_dispatch:
    inputs:
      val:
        required: false
        type: string
  workflow_call:
    inputs:
      val:
        required: false
        type: string
        default: This is default value

jobs:
  job1:
    name: 'Show inputs.val'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{inputs.val}}
