name: dispatch_test
on:
  workflow_dispatch:
    inputs:
      val:
        required: false
        type: string
  workflow_call:
    inputs:
      val:
        required: false
        type: string
        default: defaultdayo
env:
  default_val: hogepiyo
  HOGE: hohoho

jobs:
  job1:
    name: '[HELP] help me'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{inputs.val || env.default_val}}
      - uses: actions/checkout@v4
      - run: bash test.sh
      - run: printenv
