name: dispatch_test
on:
  workflow_dispatch:
    inputs:
      labels:
        description: labels
        required: false
        type: string

jobs:
  job1:
    if: ${{inputs.labels != ''}}
    runs-on: ${{inputs.labels}}
    steps:
      - run: |
          echo ${{inputs.mode}}
    
