name: dispatch_test
on:
  workflow_dispatch:
    inputs:
      mode:
        description: select a mode
        required: true
        type: choice
        options:
          - "[HOGE] hogepiyo1"
      labels:
        description: labels
        required: true
        type: string

jobs:
  job1:
    runs-on: ${{inputs.labels}}
    steps:
      - run: |
          echo ${{inputs.mode}}
    
