name: dispatch_test
on:
  workflow_dispatch:
    inputs:
      labels:
        description: labels
        required: false
        type: string
      val:
        required: false
        type: string
env:
  default_val: hogepiyo

jobs:
  job1:
    name: '[HELP] help me'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{inputs.val || env.default_val}}
    
