name: dispatch_test
on:
  workflow_dispatch:

jobs:
  caller:
    name: 'Call other repo workflow via workflow_call'
    uses: TE-ShungoHigashi/private_testrepo/.github/workflows/helloworld.yml@main
    with:
      name: "John"
    secrets: inherit
