name: matrix runs-on
on:
  workflow_dispatch:

jobs:
  job1:
    name: matrix runs-on
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      
