name: Multiline str check

on:
  workflow_dispatch:

jobs:
  multi-line-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -n "Checking..."
          sleep 3
          echo "Done!"
      - uses: actions/checkout@v4
      - env:
          var1:  senscord-edc-t4.*\.tar\.gz
        run: echo "$var1"
      - id: output-line
        run: |
          #echo "test1=aaa\nbbbb\nccc" | tee -a $GITHUB_OUTPUT
          #echo -e "test2=aaa\nbbbb\nccc" | tee -a $GITHUB_OUTPUT
          ( echo "test3<<EOF"
            echo "aaa
            bbb
            ccc"
            echo "EOF") | tee -a $GITHUB_OUTPUT

      - run: |
          #echo "test1: ${{ steps.output-line.outputs.test1 }}"
          #echo "test2: ${{ steps.output-line.outputs.test2 }}"
          echo 'test3: ${{ steps.output-line.outputs.test3 }}'
      - uses: ./.github/actions/tmp3
        with:
          input_str: ${{ steps.output-line.outputs.test3 }}
      
