name: release test

on:
  release:
    types: published

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.event.release.tag_name=${{ github.event.release.tag_name }}"
          echo "github.repository=${{ github.repository }}"
          echo "github.event.repository=${{ github.event.repository }}"
          echo "github.event.release.repository=${{ github.event.release.repository }}"
