name: summary test

on:
  workflow_dispatch:
    inputs:
      presleep:
        type: number
        default: '0'
      sleep:
        type: number
        default: '0'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          [[ -n ${{inputs.sleep}} ]] && echo nonempty || echo empty
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tmp1
      - name: first summary
        run: echo "first summary" >> $GITHUB_STEP_SUMMARY
      - name: presleep
        run: |
          sleep 30
          exit ${{inputs.presleep}}
      - name: sleep
        id: sleep
        run: |
          sleep 30
          exit ${{inputs.sleep}}
      - name: second summary
        run: echo "second summary" >> $GITHUB_STEP_SUMMARY
      - name: check outcome
        if: always()
        run: echo "${{steps.sleep.outcome}}"
        
    
