name: summary test

on:
  workflow_dispatch:
    inputs:
      presleep:
        type: string
      sleep:
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: tee
        run: |
          echo "test1=test1" | tee -a $GITHUB_OUTPUT
          echo "test2=test2" | tee -a $GITHUB_OUTPUT
      - run: |
          echo ${{ steps.tee.outputs.test1}} ${{ steps.tee.outputs.test2 }}
      - run: |
          [[ -n ${{inputs.sleep}} ]] && echo nonempty || echo empty
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tmp1
      - name: first summary
        run: echo "first summary" >> $GITHUB_STEP_SUMMARY
      - name: presleep
        run: |
          sleep 30
          exit ${{inputs.presleep}}
      - name: sleep
        id: sleep
        run: |
          sleep 30
          exit ${{inputs.sleep}}
      - name: second summary
        run: echo "second summary" >> $GITHUB_STEP_SUMMARY
      - name: check outcome
        if: always()
        run: echo "${{steps.sleep.outcome}}"
        
    
