name: list check

on:
  workflow_dispatch:

jobs:
  array_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: list
        uses: ./.github/actions/tmp3
        with:
          input_str: |
            piyo1
            piyo2

            piyo3

