name: list check

on:
  workflow_dispatch:

jobs:
  array_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: output
        run: |
          echo '```python' >> "${GITHUB_STEP_SUMMARY}"
          ls -la . >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          echo "aaaa
          bbb
          ccc" >> "${GITHUB_STEP_SUMMARY}"
          cat <<'EOC' >> "${GITHUB_STEP_SUMMARY}"
          This is here document
          ```bash
          echo hogehoge
          ```
          EOC
      - name: list
        uses: ./.github/actions/tmp3
        with:
          input_str: |
            piyo1
            piyo2

            piyo3

