name: upload artifact

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: this_is_name
          path: |
            test.sh
            hoge
            dir/
      
