name: upload artifact

on:
  push:
env:
  test: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{startsWith(env.test, 'f')}} ]]; then
            echo true
          else
            echo false
          fi
          if [[ ${{startsWith(env.test, 't')}} ]]; then
            echo true
          else
            echo false
          fi
          if [[ ${{startsWith(env.test, 'f')}} = 'false' ]]; then
            echo true
          else
            echo false
          fi
          if [[ ${{startsWith(env.test, 'f')}} = 'true' ]]; then
            echo true
          else
            echo false
          fi
