name: upload artifact

on:
  workflow_dispatch:
    inputs:
      content:
        type: string
env:
  test: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TEST1=hoge1" >> $GITHUB_ENV
          echo "TEST2=/${TEST1}" >> $GITHUB_ENV
      - name: test
        run:
          echo TEST1=${TEST1}
          echo TEST2=${TEST2}
      - name: restore cache
        uses: actions/cache/restore@v4
        with:
          path: dir
          key: cache_test
      - name: check content (1st)
        run: |
          [ -e dir/test.txt ] && cat dir/test.txt || { echo no file && mkdir dir }
      - name: add content
        run: |
          echo ${{inputs.content}} >> dir/test.txt
      - name: check content (2nd)
        run: |
          cat dir/test.txt
      - name: save cache
        uses: actions/cache/save@v4
        with:
          path: dir
          key: cache_test
        
