name: upload artifact

on:
  workflow_dispatch:
    inputs:
      content:
        type: string
env:
  test: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: git --version
      - uses: actions/checkout@v4
        with:
          path: hogepiyo
          sparse-checkout: dir/
          sparse-checkout-cone-mode: false
      - run: ls -R
        if: ${{ startsWith(inputs.content, 'h' == 'true' }}
      - name: Checkout mkfsimg.py
        uses: actions/checkout@v4
        with:
          repository: jrast/littlefs-python
          path: littlefs-python
          sparse-checkout: examples
          #sparse-checkout-cone-mode: false
          ref: v0.10.3
      - run: ls -R
      - run: |
          mkdir dist
          wget -nv --output-document allure-commandline.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.26.0/allure-commandline-2.26.0.tgz
          tar -xf allure-commandline.tgz --strip-components=1 --directory dist
          dist/bin/allure --help
      - run: |
          echo "TEST1=hoge1" >> $GITHUB_ENV
          echo "TEST2=/${TEST1}" >> $GITHUB_ENV
      - name: test
        run:
          echo TEST1=${TEST1}
          echo TEST2=${TEST2}
      - name: restore cache
        uses: actions/cache/restore@v4
        with:
          path: dir
          key: cache_test
      - name: check content (1st)
        run: |
          [ -e dir/test.txt ] && cat dir/test.txt || { echo "no file"; mkdir dir; }
      - name: add content
        run: |
          echo ${{inputs.content}} >> dir/test.txt
      - name: check content (2nd)
        run: |
          cat dir/test.txt
      - name: save cache
        uses: actions/cache/save@v4
        with:
          path: dir
          key: cache_test
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            botu
