name: upload artifact

on:
  push:
  workflow_dispatch:
env:
  test: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TEST1=hoge1" >> $GITHUB_ENV
          echo "TEST2=/${TEST1}" >> $GITHUB_ENV
      - run:
          echo TEST1=${TEST1}
          echo TEST2=${TEST2}
