name: upload artifact

on:
  push:
env:
  test: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{startsWith(env.test, 'f')}} ]]; then
            echo true
          else
            echo false
          fi
