name: Workflow Call Test
on:
  workflow_dispatch:
    inputs:
      val:
        description: 'Value to pass to the called workflow'
        required: true
        type: string
        default: 'default_value'

jobs:
  set_env:
    runs-on: ubuntu-latest
    outputs:
      env1: ${{ steps.set_env.outputs.env1 }}
    steps:
      - id: set_env
        run: echo "env1=hogehoge" | tee -a $GITHUB_OUTPUT

  call_1:
    name: 'Call workflow with needs'
    needs:
      - set_env
    uses: ./.github/workflows/wf_call_test_callee.yml
    with:
      call_val: ${{ needs.set_env.outputs.env1 }}

  call_2:
    name: 'Call workflow with inputs'
    uses: ./.github/workflows/wf_call_test_callee.yml
    with:
      call_val: ${{ inputs.val }}

  call_3:
    name: 'Call workflow with matrix'
    uses: ./.github/workflows/wf_call_test_callee.yml
    strategy:
      matrix:
        call_val: [ 'value1', 'value2', 'value3' ]
    with:
      call_val: ${{ matrix.call_val }}
